### ISSUE TITLE
first level 1 heading of the index.md file as page.title

### ISSUE THREAD

**Issue by iurisegtovich** [pages-themes/tactile#11]
hi, the template seems to be using my first level 1 heading of the `index.md` file as `page.title`, thus repeating the sentence in the header and in the body of the generated webpage. and ignoring whatever supplied via `title:` in the `_config` file.  not sure if a bug or a feature, but it seemed undesirable to me.

i changed 

```
          <h1>{{ page.title | default: site.title | default: site.github.repository_name }}</h1>
          <h2>{{ page.description | default: site.description | default: site.github.project_tagline }}</h2>
```

to

```
          <h1>{{ site.title | default: site.github.repository_name }}</h1>
          <h2>{{ site.description | default: site.github.project_tagline }}</h2>
```

in a local `default.html` to override the template in my repository to fit my needs.

**Comment by byrond** [comment]
I experienced a similar issue and proposed a change to just the title output, but the description may need to be updated as you described. Since `page.title` and `page.description` are always set due to the Jekyll SEO plugin, they should be used as the fallback.

See https://github.com/pages-themes/tactile/pull/18
